services:
  game:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ipc: ${IPC}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    networks:
      - asteroids-net
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
networks:
  asteroids-net:
    driver: bridge
    name: asteroids-net